"""Alembic environment — wires migrations to the app's database and ORM metadata.

The URL comes from :func:`invisable_os.store.db._resolve_url` (the same resolution
the running app uses), and the target metadata is the store's ``Base.metadata``, so
autogenerated revisions diff against the live models.
"""

from __future__ import annotations

from alembic import context
from sqlalchemy import create_engine

from invisable_os.store import models  # noqa: F401 — registers the mappers
from invisable_os.store.db import Base, _resolve_url

target_metadata = Base.metadata


def _url() -> str:
    return _resolve_url()


def run_migrations_offline() -> None:
    context.configure(
        url=_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        render_as_batch=_url().startswith("sqlite"),
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    url = _url()
    connect_args = {"check_same_thread": False} if url.startswith("sqlite") else {}
    engine = create_engine(url, future=True, connect_args=connect_args)
    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=url.startswith("sqlite"),
        )
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
